# Generated by Django 5.0.4 on 2024-04-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coffees_purchased', models.IntegerField(default=0)),
                ('coffees_received', models.IntegerField(default=0)),
            ],
        ),
    ]
